# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: GitGuardianShield
  pool:
    vmImage: 'ubuntu-latest'
  container: gitguardian/ggshield:latest
  steps:
  - script: ggshield scan ci
    env:
      GITGUARDIAN_API_KEY: $(gitguardianApiKey)