version: 2.1
orbs:
  ggshield: gitguardian/ggshield@volatile
workflows:
  main:
    jobs:
      - ggshield/scan:
          name: ggshield-scan
          base_revision: << pipeline.git.base_revision >>
          revision: <<pipeline.git.revision>>
